### ISSUE TITLE
关于训练测试数据集

### ISSUE THREAD

**Issue by NanYoMy** [FesianXu/SK-CNN#3]
你好，我能咨询一下代码所使用的测试训练数据集吗？我最近也在写这个方面的代码，但是我使用帧差特征，起码从视觉上看就非常糟糕，我看你的readme里面的中间一排绿色的图倒是蛮有规律的。

**Comment by FesianXu** [comment]
Hi, @NanYoMy 
Actually i have evaluated the code both on the `UESTC RGB-D Varying-view action database`[1] and NTU RGB+D[2]. it seems work ok.


Reference:
[1]. https://github.com/HRI-UESTC/CFM-HRI-RGB-D-action-database
[2]. https://github.com/shahroudy/NTURGB-D

**Comment by NanYoMy** [comment]
感谢感谢
