### ISSUE TITLE
may i use sk-cnn in static images?

### ISSUE THREAD

**Issue by hello-astar** [FesianXu/SK-CNN#4]
exactually i want to mark the joints in static images by any other excellent modules and get just joints data or images with joints marked .
after that, may i use sk-cnn to recognize human actions?

my image-database: http://human-pose.mpi-inf.mpg.de/#

**Comment by FesianXu** [comment]
i think you can do that by just modifying the channel from 3 to 2(usually the prediction of the pose estimation is 2D , including x and y. 3D pose estimation is not work as well as 2D pose estimation yet.)

**Comment by hello-astar** [comment]
thanks for your suggestion. i'll try it.
