### ISSUE TITLE
two stream 

### ISSUE THREAD

**Issue by young-fire** [FesianXu/SK-CNN#6]
where are  two streams and Skeleton transformer

**Comment by young-fire** [comment]
i can't find the corresponding  codes

**Comment by FesianXu** [comment]
i don't understand what `two-stream` means here. As for the skeleton transformer, maybe you should refer https://github.com/FesianXu/PLSTM first.

**Comment by young-fire** [comment]
sorry,not the same paper,sorry .tks very much
